welcome:
  message: Welcome to Solidarity
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/solidarity0
    password: root
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
